CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(35) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(40) NOT NULL,
  "password" varchar(20) NOT NULL,
  "age" int NOT NULL,
  "roles_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(60) NOT NULL,
  "level" varchar(20) NOT NULL,
  "teacher_id" int NOT NULL
);

CREATE TABLE "courses_students" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "student_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "course_id" INT GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY ("id", "student_id", "course_id")
);

CREATE TABLE "courses_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(50) NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(35) NOT NULL
);

CREATE TABLE "courses_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "course_id" INT GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY ("id", "category_id", "course_id")
);

ALTER TABLE "users" ADD FOREIGN KEY ("roles_id") REFERENCES "roles" ("id");

ALTER TABLE "courses_video" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "courses_students" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id");

ALTER TABLE "courses_students" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "users" ("id");


INSERT INTO roles (name) VALUES ('student'), ('teacher'), ('admin');
INSERT INTO categories (name) VALUES ('front end'), ('back end'), ('science');
INSERT INTO users (name, email, password, age, roles_id) VALUES ('Rodrigo', 'roayalaca25@outlook.com', '123456', 25, 1), ('Ian', 'ian33@outlook.com', '456789', 27, 2), ('George', 'george99@outlook.com', '789abc', 30, 3), ('Alejandra', 'ale33@outlook.com', 'olazagasti', 26, 2), ('Brenda', 'brenda33@outlook.com', 'brenreact123', 28, 2), ('Lizette', 'liz33@outlook.com', 'molino123', 33, 1);
INSERT INTO courses (title, description, level, teacher_id) VALUES ('HTML course', 'An introduction to HTML for beginners', 'Beginners', 2), ('React JS', 'Front end development with react', 'Intermediate', 5), ('Javascript DOM', 'Usage of DOM with JS', 'Advanced', 4);
INSERT INTO courses_video (title, url, course_id) VALUES ('HTML course', 'URL1', 1), ('React JS', 'URL2', 2), ('Javascript DOM', 'URL3', 3);
INSERT INTO courses_students (student_id, course_id) VALUES (1, 2), (6, 1);
INSERT INTO courses_categories (category_id, course_id) VALUES (1, 2), (2, 3), (3, 1);